language: python

python:
  - "3.3"
  - "2.7"

install: 
  - wget http://xmlsoft.org/sources/libxslt-1.1.28.tar.gz; tar xvf libxslt-1.1.28.tar.gz; cd libxslt-1.1.28\python; CFLAGS="-O0" python setup.py build; python setup.py install
  - pip install pytest cssutils

script:  make test
